### ISSUE TITLE
Displayed titles are not truncated

### ISSUE THREAD

**Issue by strangedev** [Pynitus-Universe/Pynitus-Mobile#1]
**Env**

Firefox 51, potentially affecting all platforms.

**Description**

When viewing Tracks / Artists / Albums and the displayed title length exceeds the available screen estate, the titles are not truncated but overlay with neighboring UI elements.

**Steps to reproduce**

Initialize the DB to contain Tracks w/ titles containing 32 characters.

**Fix**

Determine the amount of horizontal space titles can take in list view and truncate the title strings accordingly, for example with trailing dots: ...

**Comment by pdrd** [comment]
Fixed in d5a8a1f0d4ce310e853ce7cded223fe476212e46.
